EXECUTOR: "LiGT_Executor"
## Training param
DEVICE: "cuda"

SAVE: TRUE
SAVE_PATH: "./ligt_base_docvqa/"

LR: 0.00005
BETAS: 
  - 0.9
  - 0.98

warmup_step: 1000

NUM_EPOCHS: 5
TRAIN_BATCH_SIZE: 8
EVAL_BATCH_SIZE: 16
PREDICT_BATCH_SIZE: 16

max_predict_length: 128
max_eval_length: 128

get_predict_score: FALSE

##DATA
ocr_path: "DocVQA_ocr"

max_input_length: 512
max_output_length: 128

NUMWORKERS: 2

ocrf_path: "./vietocr/ocrf/"

qa_train_path: "DocVQA_train.csv"
qa_val_path: "DocVQA_val.csv"
qa_predict_path:  "DocVQA_test.csv"

## MODEL
MODEL_CLASS: "LiGT"

MODEL_MOD_CONFIG_CLASS:  # model modified config class

backbone_name: "google-t5/t5-base"



